services:
  gateway:
    container_name: gateway
    build:
      context: gateway
    volumes:
      - ./gateway/src/krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - cards
      - packs
      - game

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/src:/usr/share/nginx:ro
    ports:
      - "80:80"
    depends_on:
      - gateway

  cards-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - cards_data:/var/lib/postgresql/data

  packs-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - packs_data:/var/lib/postgresql/data

  game-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - game_data:/var/lib/postgresql/data

  cards:
    build:
      context: services/cards_service
    volumes:
      - ./services/cards_service/src:/app/src
      - ./services/cards_service/alembic:/app/alembic
    env_file:
      - services/cards_service/.env
    command: ["sh", "-c", "alembic upgrade head && uvicorn cards.main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      - cards-db
    ports:
      - "8001:8000"

  packs:
    build:
      context: services/packs_service
    volumes:
      - ./services/packs_service/src:/app/src
      - ./services/packs_service/alembic:/app/alembic
    env_file:
      - services/packs_service/.env
    command: ["sh", "-c", "alembic upgrade head && uvicorn packs.main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      - packs-db
    ports:
      - "8002:8000"
      - "50052:50051"

  game:
    build:
      context: services/game_service
    volumes:
      - ./services/game_service/src:/app/src
      - ./services/game_service/alembic:/app/alembic
    env_file:
      - services/game_service/.env
    command: ["sh", "-c", "alembic upgrade head && uvicorn game.main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      - game-db
    ports:
      - "8003:8000"

volumes:
  cards_data:
  packs_data:
  game_data: