CREATE SCHEMA IF NOT EXISTS cards;
CREATE USER cards_user WITH PASSWORD 'cards_password';
GRANT ALL PRIVILEGES ON SCHEMA cards TO cards_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA cards
GRANT ALL ON TABLES TO cards_user;


CREATE SCHEMA IF NOT EXISTS packs;
CREATE USER packs_user WITH PASSWORD 'packs_password';
GRANT ALL PRIVILEGES ON SCHEMA packs TO packs_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA packs
GRANT ALL ON TABLES TO packs_user;
