"""Add field total to Pack model

Revision ID: da516802b38b
Revises: 359b13c6c0d8
Create Date: 2026-01-31 13:12:05.788671

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da516802b38b'
down_revision: Union[str, Sequence[str], None] = '359b13c6c0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('total', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'total')
    # ### end Alembic commands ###
