"""Packs add creator column

Revision ID: 571542d30982
Revises: da516802b38b
Create Date: 2026-04-18 13:44:35.658399

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '571542d30982'
down_revision: Union[str, Sequence[str], None] = 'da516802b38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('creator', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'creator')
    # ### end Alembic commands ###
