routes:
  - id: 100
    name: frontend_root
    uri: /*
    methods: [ GET ]
    upstream:
      type: roundrobin
      nodes:
        "frontend:80": 1

  - id: 1
    name: cards_post_wildcard
    uri: /api/v1/cards/*
    methods: [POST]
    upstream:
      type: roundrobin
      nodes:
        "cards:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 15
        burst: 30
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 300
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 2
    name: game_ws
    uri: /ws/game/*
    methods: [ GET ]
    enable_websocket: true

    upstream:
      type: roundrobin
      nodes:
        "game:8000": 1

      timeout:
        connect: 5
        send: 3600
        read: 3600

      keepalive_pool:
        size: 20
        idle_timeout: 60
        requests: 10000

    plugins:
      limit-req:
        rate: 10
        burst: 20
        key: remote_addr
        rejected_code: 429

  - id: 3
    name: auth
    uri: /api/v1/auth/*
    methods: [GET, POST]
    upstream:
      type: roundrobin
      nodes:
        "auth:8000": 1
    plugins:
      limit-req:
        rate: 15
        burst: 30
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 300
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 4
    name: register
    uri: /api/v1/auth/register/
    methods: [POST]
    upstream:
      type: roundrobin
      nodes:
        "auth:8000": 1
    plugins:
      limit-req:
        rate: 5
        burst: 10
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 30
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 5
    name: game
    uri: /api/v1/game
    methods: [POST]
    upstream:
      type: roundrobin
      nodes:
        "game:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 15
        burst: 30
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 300
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 6
    name: packs_get
    uri: /api/v1/packs
    methods: [GET]
    upstream:
      type: roundrobin
      nodes:
        "packs:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 30
        burst: 60
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 600
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 7
    name: packs_post
    uri: /api/v1/packs
    methods: [POST]
    upstream:
      type: roundrobin
      nodes:
        "packs:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 15
        burst: 30
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 300
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 8
    name: packs_get_wildcard
    uri: /api/v1/packs/*
    methods: [GET]
    upstream:
      type: roundrobin
      nodes:
        "packs:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 30
        burst: 60
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 600
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 9
    name: packs_put_wildcard
    uri: /api/v1/packs/*
    methods: [PUT]
    upstream:
      type: roundrobin
      nodes:
        "packs:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 15
        burst: 30
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 300
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 10
    name: packs_delete_wildcard
    uri: /api/v1/packs/*
    methods: [DELETE]
    upstream:
      type: roundrobin
      nodes:
        "packs:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 5
        burst: 10
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 100
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 11
    name: cards_get
    uri: /api/v1/cards
    methods: [GET]
    upstream:
      type: roundrobin
      nodes:
        "cards:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 30
        burst: 60
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 600
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 12
    name: cards_post
    uri: /api/v1/cards
    methods: [POST]
    upstream:
      type: roundrobin
      nodes:
        "cards:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 15
        burst: 30
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 300
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 13
    name: cards_delete
    uri: /api/v1/cards
    methods: [DELETE]
    upstream:
      type: roundrobin
      nodes:
        "cards:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 5
        burst: 10
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 100
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429

  - id: 14
    name: auth_me
    uri: /api/v1/auth/me
    methods: [GET]
    upstream:
      type: roundrobin
      nodes:
        "auth:8000": 1
    plugins:
      forward-auth:
        uri: http://auth:8000/api/v1/auth/verify
        request_headers: [Authorization]
        upstream_headers: [X-User-Id]

      limit-req:
        rate: 30
        burst: 60
        key: remote_addr
        rejected_code: 429

      limit-count:
        count: 600
        time_window: 60
        key: remote_addr
        policy: local
        rejected_code: 429
