#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<EOF

CREATE USER ${AUTH_APP_USER}
WITH PASSWORD '${AUTH_APP_PASSWORD}';

GRANT CONNECT ON DATABASE ${POSTGRES_DB}
TO ${AUTH_APP_USER};

GRANT USAGE ON SCHEMA public
TO ${AUTH_APP_USER};

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO ${AUTH_APP_USER};

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO ${AUTH_APP_USER};

ALTER DEFAULT PRIVILEGES
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ${AUTH_APP_USER};

ALTER DEFAULT PRIVILEGES
IN SCHEMA public
GRANT USAGE, SELECT, UPDATE
ON SEQUENCES TO ${AUTH_APP_USER};

EOF