"""Add new column position and unique constraint uix_pack_position

Revision ID: a95e2f1507c5
Revises: bc461b3837b3
Create Date: 2026-01-30 14:29:28.058081

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a95e2f1507c5'
down_revision: Union[str, Sequence[str], None] = 'bc461b3837b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('position', sa.Integer(), nullable=False))
    op.create_unique_constraint('uix_pack_position', 'card', ['pack_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_pack_position', 'card', type_='unique')
    op.drop_column('card', 'position')
    # ### end Alembic commands ###
